# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: mysql
    port: 3306
  clusterIP: None

# pod-name.service-name.namespace.svc.cluster.local
# {{ .Chart.Name }}-0.{{ .Chart.Name }}.{{ .Values.namespace.name }}.svc.cluster.local
