apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-{{ .Values.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  volumeName: {{ .Chart.Name }}-{{ .Values.pv.name }}
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
