apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.clusterIP.port }}
    targetPort: {{ .Values.service.clusterIP.targetPort }}
